/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SupportImport } from './routes/support'
import { Route as HelpImport } from './routes/help'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as TicketsIndexImport } from './routes/tickets/index'
import { Route as RegisterIndexImport } from './routes/register/index'
import { Route as PurchasesIndexImport } from './routes/purchases/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as FavouritesIndexImport } from './routes/favourites/index'
import { Route as ExploreIndexImport } from './routes/explore/index'
import { Route as UUIdImport } from './routes/u/$uId'
import { Route as TicketsTIdImport } from './routes/tickets/$tId'
import { Route as PurchasesPIdImport } from './routes/purchases/$pId'
import { Route as HostStaffImport } from './routes/host/staff'
import { Route as HostJoinImport } from './routes/host/join'
import { Route as HostDashboardImport } from './routes/host/dashboard'
import { Route as EventEventIdIndexImport } from './routes/event/$eventId/index'
import { Route as HostDashboardEventIdImport } from './routes/host/dashboard_.event.$id'

// Create/Update Routes

const SupportRoute = SupportImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRoute,
} as any)

const HelpRoute = HelpImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TicketsIndexRoute = TicketsIndexImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRoute,
} as any)

const RegisterIndexRoute = RegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const PurchasesIndexRoute = PurchasesIndexImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const FavouritesIndexRoute = FavouritesIndexImport.update({
  id: '/favourites/',
  path: '/favourites/',
  getParentRoute: () => rootRoute,
} as any)

const ExploreIndexRoute = ExploreIndexImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRoute,
} as any)

const UUIdRoute = UUIdImport.update({
  id: '/u/$uId',
  path: '/u/$uId',
  getParentRoute: () => rootRoute,
} as any)

const TicketsTIdRoute = TicketsTIdImport.update({
  id: '/tickets/$tId',
  path: '/tickets/$tId',
  getParentRoute: () => rootRoute,
} as any)

const PurchasesPIdRoute = PurchasesPIdImport.update({
  id: '/purchases/$pId',
  path: '/purchases/$pId',
  getParentRoute: () => rootRoute,
} as any)

const HostStaffRoute = HostStaffImport.update({
  id: '/host/staff',
  path: '/host/staff',
  getParentRoute: () => rootRoute,
} as any)

const HostJoinRoute = HostJoinImport.update({
  id: '/host/join',
  path: '/host/join',
  getParentRoute: () => rootRoute,
} as any)

const HostDashboardRoute = HostDashboardImport.update({
  id: '/host/dashboard',
  path: '/host/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const EventEventIdIndexRoute = EventEventIdIndexImport.update({
  id: '/event/$eventId/',
  path: '/event/$eventId/',
  getParentRoute: () => rootRoute,
} as any)

const HostDashboardEventIdRoute = HostDashboardEventIdImport.update({
  id: '/host/dashboard_/event/$id',
  path: '/host/dashboard/event/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpImport
      parentRoute: typeof rootRoute
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportImport
      parentRoute: typeof rootRoute
    }
    '/host/dashboard': {
      id: '/host/dashboard'
      path: '/host/dashboard'
      fullPath: '/host/dashboard'
      preLoaderRoute: typeof HostDashboardImport
      parentRoute: typeof rootRoute
    }
    '/host/join': {
      id: '/host/join'
      path: '/host/join'
      fullPath: '/host/join'
      preLoaderRoute: typeof HostJoinImport
      parentRoute: typeof rootRoute
    }
    '/host/staff': {
      id: '/host/staff'
      path: '/host/staff'
      fullPath: '/host/staff'
      preLoaderRoute: typeof HostStaffImport
      parentRoute: typeof rootRoute
    }
    '/purchases/$pId': {
      id: '/purchases/$pId'
      path: '/purchases/$pId'
      fullPath: '/purchases/$pId'
      preLoaderRoute: typeof PurchasesPIdImport
      parentRoute: typeof rootRoute
    }
    '/tickets/$tId': {
      id: '/tickets/$tId'
      path: '/tickets/$tId'
      fullPath: '/tickets/$tId'
      preLoaderRoute: typeof TicketsTIdImport
      parentRoute: typeof rootRoute
    }
    '/u/$uId': {
      id: '/u/$uId'
      path: '/u/$uId'
      fullPath: '/u/$uId'
      preLoaderRoute: typeof UUIdImport
      parentRoute: typeof rootRoute
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreIndexImport
      parentRoute: typeof rootRoute
    }
    '/favourites/': {
      id: '/favourites/'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/purchases/': {
      id: '/purchases/'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesIndexImport
      parentRoute: typeof rootRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsIndexImport
      parentRoute: typeof rootRoute
    }
    '/event/$eventId/': {
      id: '/event/$eventId/'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/host/dashboard_/event/$id': {
      id: '/host/dashboard_/event/$id'
      path: '/host/dashboard/event/$id'
      fullPath: '/host/dashboard/event/$id'
      preLoaderRoute: typeof HostDashboardEventIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/support': typeof SupportRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/join': typeof HostJoinRoute
  '/host/staff': typeof HostStaffRoute
  '/purchases/$pId': typeof PurchasesPIdRoute
  '/tickets/$tId': typeof TicketsTIdRoute
  '/u/$uId': typeof UUIdRoute
  '/explore': typeof ExploreIndexRoute
  '/favourites': typeof FavouritesIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/purchases': typeof PurchasesIndexRoute
  '/register': typeof RegisterIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/event/$eventId': typeof EventEventIdIndexRoute
  '/host/dashboard/event/$id': typeof HostDashboardEventIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/support': typeof SupportRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/join': typeof HostJoinRoute
  '/host/staff': typeof HostStaffRoute
  '/purchases/$pId': typeof PurchasesPIdRoute
  '/tickets/$tId': typeof TicketsTIdRoute
  '/u/$uId': typeof UUIdRoute
  '/explore': typeof ExploreIndexRoute
  '/favourites': typeof FavouritesIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/purchases': typeof PurchasesIndexRoute
  '/register': typeof RegisterIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/event/$eventId': typeof EventEventIdIndexRoute
  '/host/dashboard/event/$id': typeof HostDashboardEventIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/help': typeof HelpRoute
  '/support': typeof SupportRoute
  '/host/dashboard': typeof HostDashboardRoute
  '/host/join': typeof HostJoinRoute
  '/host/staff': typeof HostStaffRoute
  '/purchases/$pId': typeof PurchasesPIdRoute
  '/tickets/$tId': typeof TicketsTIdRoute
  '/u/$uId': typeof UUIdRoute
  '/explore/': typeof ExploreIndexRoute
  '/favourites/': typeof FavouritesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/purchases/': typeof PurchasesIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/event/$eventId/': typeof EventEventIdIndexRoute
  '/host/dashboard_/event/$id': typeof HostDashboardEventIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/help'
    | '/support'
    | '/host/dashboard'
    | '/host/join'
    | '/host/staff'
    | '/purchases/$pId'
    | '/tickets/$tId'
    | '/u/$uId'
    | '/explore'
    | '/favourites'
    | '/login'
    | '/profile'
    | '/purchases'
    | '/register'
    | '/tickets'
    | '/event/$eventId'
    | '/host/dashboard/event/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/help'
    | '/support'
    | '/host/dashboard'
    | '/host/join'
    | '/host/staff'
    | '/purchases/$pId'
    | '/tickets/$tId'
    | '/u/$uId'
    | '/explore'
    | '/favourites'
    | '/login'
    | '/profile'
    | '/purchases'
    | '/register'
    | '/tickets'
    | '/event/$eventId'
    | '/host/dashboard/event/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/help'
    | '/support'
    | '/host/dashboard'
    | '/host/join'
    | '/host/staff'
    | '/purchases/$pId'
    | '/tickets/$tId'
    | '/u/$uId'
    | '/explore/'
    | '/favourites/'
    | '/login/'
    | '/profile/'
    | '/purchases/'
    | '/register/'
    | '/tickets/'
    | '/event/$eventId/'
    | '/host/dashboard_/event/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HelpRoute: typeof HelpRoute
  SupportRoute: typeof SupportRoute
  HostDashboardRoute: typeof HostDashboardRoute
  HostJoinRoute: typeof HostJoinRoute
  HostStaffRoute: typeof HostStaffRoute
  PurchasesPIdRoute: typeof PurchasesPIdRoute
  TicketsTIdRoute: typeof TicketsTIdRoute
  UUIdRoute: typeof UUIdRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  FavouritesIndexRoute: typeof FavouritesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  PurchasesIndexRoute: typeof PurchasesIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
  EventEventIdIndexRoute: typeof EventEventIdIndexRoute
  HostDashboardEventIdRoute: typeof HostDashboardEventIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HelpRoute: HelpRoute,
  SupportRoute: SupportRoute,
  HostDashboardRoute: HostDashboardRoute,
  HostJoinRoute: HostJoinRoute,
  HostStaffRoute: HostStaffRoute,
  PurchasesPIdRoute: PurchasesPIdRoute,
  TicketsTIdRoute: TicketsTIdRoute,
  UUIdRoute: UUIdRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  FavouritesIndexRoute: FavouritesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  PurchasesIndexRoute: PurchasesIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
  EventEventIdIndexRoute: EventEventIdIndexRoute,
  HostDashboardEventIdRoute: HostDashboardEventIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/help",
        "/support",
        "/host/dashboard",
        "/host/join",
        "/host/staff",
        "/purchases/$pId",
        "/tickets/$tId",
        "/u/$uId",
        "/explore/",
        "/favourites/",
        "/login/",
        "/profile/",
        "/purchases/",
        "/register/",
        "/tickets/",
        "/event/$eventId/",
        "/host/dashboard_/event/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/help": {
      "filePath": "help.tsx"
    },
    "/support": {
      "filePath": "support.tsx"
    },
    "/host/dashboard": {
      "filePath": "host/dashboard.tsx"
    },
    "/host/join": {
      "filePath": "host/join.tsx"
    },
    "/host/staff": {
      "filePath": "host/staff.tsx"
    },
    "/purchases/$pId": {
      "filePath": "purchases/$pId.tsx"
    },
    "/tickets/$tId": {
      "filePath": "tickets/$tId.tsx"
    },
    "/u/$uId": {
      "filePath": "u/$uId.tsx"
    },
    "/explore/": {
      "filePath": "explore/index.tsx"
    },
    "/favourites/": {
      "filePath": "favourites/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    },
    "/purchases/": {
      "filePath": "purchases/index.tsx"
    },
    "/register/": {
      "filePath": "register/index.tsx"
    },
    "/tickets/": {
      "filePath": "tickets/index.tsx"
    },
    "/event/$eventId/": {
      "filePath": "event/$eventId/index.tsx"
    },
    "/host/dashboard_/event/$id": {
      "filePath": "host/dashboard_.event.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
